"""initial schema

Revision ID: 34c9cb6b3829
Revises: 
Create Date: 2026-09-23 06:47:34.391513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c9cb6b3829'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', name='uq_agency_id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_client_id_agency')
    )
    op.create_index('ix_clients_agency', 'clients', ['agency_id'], unique=False)
    op.create_table('invites',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('agency_admin', 'agency_member', 'client_user', name='role'), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'revoked', name='invitestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index('ix_invites_agency', 'invites', ['agency_id'], unique=False)
    # Enforces "invite races" at the DB level: at most one PENDING invite
    # per (agency, email) can ever exist. Resending reuses that row instead
    # of racing this constraint with a fresh insert.
    op.execute(
        "CREATE UNIQUE INDEX uq_invite_pending_per_agency_email "
        "ON invites (agency_id, email) WHERE status = 'pending'"
    )
    op.create_table('memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('role', sa.Enum('agency_admin', 'agency_member', 'client_user', name='role'), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_membership_id_agency'),
    sa.UniqueConstraint('user_id', 'agency_id', 'id', name='uq_membership_lookup'),
    sa.UniqueConstraint('user_id', 'agency_id', name='uq_membership_user_agency')
    )
    op.create_index('ix_memberships_agency', 'memberships', ['agency_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('client_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['client_id', 'agency_id'], ['clients.id', 'clients.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_project_id_agency')
    )
    op.create_index('ix_projects_agency', 'projects', ['agency_id'], unique=False)
    op.create_table('project_memberships',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['project_id', 'agency_id'], ['projects.id', 'projects.agency_id'], ),
    sa.ForeignKeyConstraint(['user_id', 'agency_id'], ['memberships.user_id', 'memberships.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'user_id', name='uq_projectmember_once')
    )
    op.create_index('ix_projmem_agency', 'project_memberships', ['agency_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('project_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('todo', 'in_progress', 'review', 'done', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', 'urgent', name='taskpriority'), nullable=False),
    sa.Column('assignee_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('visibility', sa.Enum('internal', 'client_visible', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['assignee_user_id', 'agency_id'], ['memberships.user_id', 'memberships.agency_id'], ),
    sa.ForeignKeyConstraint(['project_id', 'agency_id'], ['projects.id', 'projects.agency_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'agency_id', name='uq_task_id_agency')
    )
    op.create_index('ix_tasks_agency', 'tasks', ['agency_id'], unique=False)
    op.create_index('ix_tasks_project', 'tasks', ['project_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('author_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('internal', 'client_visible', name='visibility'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['author_user_id', 'agency_id'], ['memberships.user_id', 'memberships.agency_id'], ),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_agency', 'comments', ['agency_id'], unique=False)
    op.create_index('ix_comments_task', 'comments', ['task_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('uploaded_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('visibility', sa.Enum('internal', 'client_visible', name='visibility'), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'needs_changes', name='approvalstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_user_id', 'agency_id'], ['memberships.user_id', 'memberships.agency_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_files_agency', 'files', ['agency_id'], unique=False)
    op.create_index('ix_files_task', 'files', ['task_id'], unique=False)
    op.create_table('time_entries',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('agency_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('task_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['task_id', 'agency_id'], ['tasks.id', 'tasks.agency_id'], ),
    sa.ForeignKeyConstraint(['user_id', 'agency_id'], ['memberships.user_id', 'memberships.agency_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_time_entries_agency', 'time_entries', ['agency_id'], unique=False)
    op.create_index('ix_time_entries_task', 'time_entries', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_time_entries_task', table_name='time_entries')
    op.drop_index('ix_time_entries_agency', table_name='time_entries')
    op.drop_table('time_entries')
    op.drop_index('ix_files_task', table_name='files')
    op.drop_index('ix_files_agency', table_name='files')
    op.drop_table('files')
    op.drop_index('ix_comments_task', table_name='comments')
    op.drop_index('ix_comments_agency', table_name='comments')
    op.drop_table('comments')
    op.drop_index('ix_tasks_project', table_name='tasks')
    op.drop_index('ix_tasks_agency', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('ix_projmem_agency', table_name='project_memberships')
    op.drop_table('project_memberships')
    op.drop_index('ix_projects_agency', table_name='projects')
    op.drop_table('projects')
    op.drop_index('ix_memberships_agency', table_name='memberships')
    op.drop_table('memberships')
    op.execute("DROP INDEX IF EXISTS uq_invite_pending_per_agency_email")
    op.drop_index('ix_invites_agency', table_name='invites')
    op.drop_table('invites')
    op.drop_index('ix_clients_agency', table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('agencies')
    # ### end Alembic commands ###
